### ISSUE TITLE
H2 Database - MVStoreException: The write format 1 is smaller than the supported format 3

### ISSUE THREAD

**Issue by supertakeru** [xCykrix/DynamicLights#17]
Plugin needs an update to 1.21.1

**Comment by xCykrix** [comment]
Latest ProtocolLib: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by supertakeru** [comment]
I get this error, what do you think of it?

[16:15:51] [Server thread/INFO]: [DynamicLights] Enabling DynamicLights v1.0.7
[16:15:51] [Server thread/ERROR]: Error occurred while enabling DynamicLights v1.0.7 (Is it up to date?)
com.shaded._100.org.h2.mvstore.MVStoreException: The write format 1 is smaller than the supported format 3 [2.3.230/5]
	at DynamicLights-1.0.7.jar/com.shaded._100.org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996) ~[DynamicLights-1.0.7.jar:?]
	at DynamicLights-1.0.7.jar/com.shaded._100.org.h2.mvstore.FileStore.getUnsupportedWriteFormatException(FileStore.java:943) ~[DynamicLights-1.0.7.jar:?]
	at DynamicLights-1.0.7.jar/com.shaded._100.org.h2.mvstore.FileStore.processCommonHeaderAttributes(FileStore.java:547) ~[DynamicLights-1.0.7.jar:?]
	at DynamicLights-1.0.7.jar/com.shaded._100.org.h2.mvstore.RandomAccessStore.readStoreHeader(RandomAccessStore.java:227) ~[DynamicLights-1.0.7.jar:?]
	at DynamicLights-1.0.7.jar/com.shaded._100.org.h2.mvstore.FileStore.start(FileStore.java:916) ~[DynamicLights-1.0.7.jar:?]
	at DynamicLights-1.0.7.jar/com.shaded._100.org.h2.mvstore.MVStore.<init>(MVStore.java:289) ~[DynamicLights-1.0.7.jar:?]
	at DynamicLights-1.0.7.jar/com.shaded._100.org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035) ~[DynamicLights-1.0.7.jar:?]
	at DynamicLights-1.0.7.jar/com.github.xcykrix.plugincommon.api.H2MVStoreAPI.initialize(H2MVStoreAPI.java:32) ~[DynamicLights-1.0.7.jar:?]
	at DynamicLights-1.0.7.jar/com.github.xcykrix.plugincommon.PluginCommon.onEnable(PluginCommon.java:30) ~[DynamicLights-1.0.7.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:15:51] [Server thread/INFO]: [DynamicLights] Disabling DynamicLights v1.0.7
[16:15:51] [Server thread/ERROR]: Error occurred while disabling DynamicLights v1.0.7
java.lang.NullPointerException: Cannot invoke "com.shaded._100.org.h2.mvstore.MVStore.close()" because "this.store" is null
	at DynamicLights-1.0.7.jar/com.github.xcykrix.plugincommon.api.H2MVStoreAPI.shutdown(H2MVStoreAPI.java:40) ~[DynamicLights-1.0.7.jar:?]
	at DynamicLights-1.0.7.jar/com.github.xcykrix.plugincommon.PluginCommon.onDisable(PluginCommon.java:62) ~[DynamicLights-1.0.7.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by xCykrix** [comment]
Thanks for the error log. There appears to be some breaking changes by the flat file database provider (h2store) that I chose that I need to address. I will publish an update to address with this soon.

**Comment by xCykrix** [comment]
Work has been completed to address this issue and merged to main. Pending release. I have to do a bit more testing for compatibility as I made quite a few fundamental changes.

**Comment by xCykrix** [comment]
This issue has been resolved in v1.1.0. Due to backend the above noted backend changes, I had to add some additional logic to resolve this issue.

You will receive a message "Failed to load h2store. Database corrupted or v1 database format was provided." on the next boot that can be safely disregarded.

https://www.spigotmc.org/resources/dynamiclights.110707/update?update=558010
https://github.com/xCykrix/DynamicLights/releases/tag/v1.1.0

There are guides you can follow to migrate, but I would just leave it as-is as the database in this case is only used for player settings and is non-critical.
