### ISSUE TITLE
(BUG): Does not work on 1.21.3

### ISSUE THREAD

**Issue by ender1324** [xCykrix/DynamicLights#19]
### Report Context

The mod does not currently work on 1.21.3 while the spigot description mentions it works on 1.21.x

### Installed Version

1.1.0

### System Environment

Windows 11

### Steps to Reproduce

Install mod on PaperMC 1.21.3

### Error Message

[09:22:26] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.3.0
[09:22:26] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.21.3) has not yet been tested! Proceed with caution.
[09:22:26] [Server thread/INFO]: [Sit] Loading server plugin Sit v1.7.1
[09:22:26] [Server thread/INFO]: [DynamicLights] Loading server plugin DynamicLights v1.1.0
[09:22:26] [Server thread/ERROR]: [DynamicLights] Error initializing plugin 'DynamicLights.jar' in folder 'plugins/.paper-remapped' (Is it up to date?)
dist.xCykrix.shade.dev.jorel.commandapi.exceptions.UnsupportedVersionException: This version of Minecraft is unsupported: 1.21.3
at DynamicLights.jar/dist.xCykrix.shade.dev.jorel.commandapi.CommandAPIVersionHandler.getPlatform(CommandAPIVersionHandler.java:71) ~[DynamicLights.jar:?]
at DynamicLights.jar/dist.xCykrix.shade.dev.jorel.commandapi.CommandAPI.onLoad(CommandAPI.java:112) ~[DynamicLights.jar:?]
at DynamicLights.jar/github.xCykrix.DevkitPlugin.onLoad(DevkitPlugin.java:18) ~[DynamicLights.jar:?]
at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.21.3.jar:1.21.3-DEV-fcb6c72]
at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.21.3.jar:1.21.3-DEV-fcb6c72]
at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.21.3.jar:1.21.3-DEV-fcb6c72]
at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.3.jar:1.21.3-DEV-fcb6c72]
at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:549) ~[paper-1.21.3.jar:1.21.3-DEV-fcb6c72]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:289) ~[paper-1.21.3.jar:1.21.3-DEV-fcb6c72]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[paper-1.21.3.jar:1.21.3-DEV-fcb6c72]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-DEV-fcb6c72]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Please affirm the following options.

- [X] I Agree to the [Code of Conduct](./CODE_OF_CONDUCT.md)
- [X] I Agree to the [Contributing Guidelines](./CONTRIBUTING.md)
- [X] I Agree to the [Security Reporting Guidelines](./SECURITY.md)

**Comment by xCykrix** [comment]
@ender1324 Thanks for submitting the issue. Fix has been implemented and will be published in v1.2.0 along with a feature request. Keep an eye our (probably) later today!

**Comment by xCykrix** [comment]
Released in v1.2.0.

https://www.spigotmc.org/resources/dynamiclights.110707/
https://github.com/xCykrix/DynamicLights/releases/tag/v1.2.0
